### ISSUE TITLE
Add before-script and after-script hooks

### ISSUE THREAD

**Issue by kelunik** [MacFJA/PharBuilder#17]
Would be nice if it could run `git describe --tags` optionally and define a version constant like `PHAR_BUILDER_GIT_VERSION`. It would remove the need to always change a file before tagging a new release.

Might as well be done by using a script to release new versions.

**Comment by MacFJA** [comment]
I'm not sure to understand what you try to do :confused:

**Comment by kelunik** [comment]
I want to provide a command line command like `acme-client version` that shows the current version. In case it's a nightly build (not one from a tag), version with `git describe --tags` would be something like `v0.2.4-3-ga05a4f8`. Since the packaged version doesn't have any `.git` info available, I need to package it somehow.

I could use a script that gets that information and builds the phar afterwards, but it would be nice if there was support directly in here, which would avoid the need for an extra script.

**Comment by kelunik** [comment]
My current proposal would be something like

```
"before-script": [
    "git describe --tags > build/version.txt"
],
"after-script": [
    "rm build/version.txt",
    "chmod +x build/acme-client.phar"
]
```

in the `"extra"` section in the `composer.json`.

**Comment by MacFJA** [comment]
Something similar to Composer event script, why not.

## 

Another idea is to create a new constant in the phar stub (bootstrap) code.
something like:

``` php
$this->phar->setStub(
    '#!/usr/bin/env php' . PHP_EOL .
    '<?php Phar::mapPhar(); ' . 
    (null === $constant?'':'define(\'PHAR_VERSION\', \''.addslashes($constant).'\');') . 
    'include "phar://' . $this->alias . '/' . $this->stubFile .
    '"; __HALT_COMPILER(); ?>'
);
```

And in the console call:

``` sh
$ phar-builder package --version=`git describe --tags`
```

## 

But your proposal allow to have event based addition action/control which can be lot more flexible

**Comment by MacFJA** [comment]
@kelunik, I made a first version of the hooks/event implementation (see e6ebea5).

I have to finish the documentation about it.

**Comment by kelunik** [comment]
`PHP Fatal error:  Uncaught Error: Class 'League\Event\Emitter' not found in /home/kelunik/GitHub/kelunik/acme-client/vendor/macfja/phar-builder/app/Application.php:68`

Somehow, `league/event` doesn't get installed even if it's in the composer.json.

**Comment by kelunik** [comment]
And it doesn't respect the `output-dir` configuration option anymore.

**Comment by kelunik** [comment]
Also `PHP Warning:  Declaration of MacFJA\PharBuilder\Event\ComposerAwareEvent::named($name, $composer) should be compatible with League\Event\Event::named($name) in /home/kelunik/GitHub/kelunik/acme-client/vendor/macfja/phar-builder/app/Event/ComposerAwareEvent.php on line 15`

**Comment by MacFJA** [comment]
> Also `PHP Warning:  Declaration of MacFJA\PharBuilder\Event\ComposerAwareEvent::named($name, $composer) should be compatible with League\Event\Event::named($name) in /home/kelunik/GitHub/kelunik/acme-client/vendor/macfja/phar-builder/app/Event/ComposerAwareEvent.php on line 15`

It's the second times! I really need to found a way to detect this! (Correct in 97bfa5f by the way)

**Comment by kelunik** [comment]
I think the warning is only printed in PHP 7?

**Comment by MacFJA** [comment]
Nope, it's my PHP(s) configuration: the `E_STRICT` flag is missing in `error_reporting` of my `php.ini`

**Comment by kelunik** [comment]
Did you have a look at the output dir?

**Comment by MacFJA** [comment]
Yep, normally it's corrected with the commit e5bb1ec

**Comment by kelunik** [comment]
`"league/event": "^2.1"` is missing as requirement.

**Comment by kelunik** [comment]
And another thing afterwards:

```
Uncaught Error: Class 'Neutron\SignalHandler\SignalHandler' not found
in /acme-client/vendor/macfja/phar-builder/app/Event/EventManager.php:76
```

https://packagist.org/packages/neutron/signal-handler

**Comment by kelunik** [comment]
After that, it fails with

`Warning: require(phar:///acme-client/build/acme-client.phar/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php): failed to open stream: phar error: "vendor/symfony/polyfill-mbstring/bootstrap.php" is not a file in phar "/acme-client/build/acme-client.phar" in phar:///acme-client/build/acme-client.phar/vendor/composer/autoload_real.php on line 65`

**Comment by MacFJA** [comment]
Are you sure to use the right branch for your test?

Those two dependencies are declared in the branch `events+issue-17` but not on the `master`

**Comment by kelunik** [comment]
That might be the case because I used `dev-master#hash` before, because the branch didn't work. I opened an issue: https://github.com/composer/composer/issues/5397. I guess it's related to the `+` in the branch name.

**Comment by kelunik** [comment]
Bug in Composer is gone now. Issue with `polyfill-mbstring` persists. It's required, because it's listed in `autoload.files`. I think we had that issue before? Do we need stubs for that?

**Comment by kelunik** [comment]
#21 fixes this.
