### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by blendsdk** [MacFJA/PharBuilder#2]
I am unable to run the utility.
Could you please point me to the correct direction to solve this?

I get the following exception:

``` bash
  [InvalidArgumentException]                       
  The "src/Globals.php" directory does not exist.                                                     
```

But the file above exists! (src/Globals.php)

My composer.json file is:

``` json
{
    "minimum-stability": "dev",
    "name": "gevik/myapp",
    "require": {
        "php": ">=5.5.9",
        "blendsdk/blendengine": "dev-engine2"
    },
    "autoload": {
        "psr-4": {
            "MyApp\\": "src"
        },
        "files": [
            "src/Globals.php"
        ]
    }
}
```

**Comment by MacFJA** [comment]
Thanks to report the error!

I found why you have this error.
The issue is caused by my poorly written _parser_: I assume that only **psr-4** and **psr-0** are used.
I will update the _parse_ to take in account **files** and **classmap**.

**Comment by MacFJA** [comment]
@blendsdk, I push (on master) a correction about your issue. Does it solve your issue?

**Comment by blendsdk** [comment]
Yes, thank you for the quick response :+1:
