### ISSUE TITLE
Upgrading to version 3

### ISSUE THREAD

**Issue by nadar** [MacFJA/PharBuilder#27]
Are there any plans to upgrade this project to version 3 of symfony console?

**Comment by JalfResi** [comment]
Would be very interested in this! Currently this restriction is limit us from using PharBuilder with a project using symfony/console 3.1

**Comment by kelunik** [comment]
Why? You can just use this project as a PHAR, then you don't have to care about conflicts. It never runs concurrently with the project's dependencies.

**Comment by JalfResi** [comment]
There isn't a phar file in the releases section, as detailed in issues #31 and #29, and I was hoping to include PharBuilder as a dependancy in my projects composer file

**Comment by nadar** [comment]
Sadly i assume this project is inactive. Maybe someone should fork and upgrade to version 3 :-)

**Comment by MacFJA** [comment]
@nadar Sorry, I'm a bit late on this.
I will be back on this project soon
