### ISSUE TITLE
Fatal Error on Startup

### ISSUE THREAD

**Issue by kelunik** [MacFJA/PharBuilder#3]
Running

```
vendor/bin/phar-builder package composer.json
```

with PHP 7.0.3 results in

```
PHP Warning:  Declaration of MacFJA\PharBuilder\Commands\Base::validateName($value, Symfony\Component\Console\Output\OutputInterface $output) should be compatible with Symfony\Component\Console\Command\Command::validateName($name) in /home/kelunik/GitHub/kelunik/acme-client/vendor/macfja/phar-builder/app/Commands/Base.php on line 289

PHP Fatal error:  Uncaught Symfony\Component\Console\Exception\InvalidArgumentException: Incorrectly nested style tag found. in /home/kelunik/GitHub/kelunik/acme-client/vendor/symfony/console/Formatter/OutputFormatterStyleStack.php:87
```

**Comment by MacFJA** [comment]
The first error is a function name conflict.
@kelunik, can you retry with the commit 43a65a8 ?

---

For the second error, without backtrace it will be hard to find out what cause it.
Let's hope that the first error is the cause.

**Comment by kelunik** [comment]
```
[14:06:49][550][~/GitHub/kelunik/acme-client] $ vendor/bin/phar-builder package composer.json 

PHP Fatal error:  Uncaught Symfony\Component\Console\Exception\InvalidArgumentException: Incorrectly nested style tag found. in /home/kelunik/GitHub/kelunik/acme-client/vendor/symfony/console/Formatter/OutputFormatterStyleStack.php:87
Stack trace:
#0 /home/kelunik/GitHub/kelunik/acme-client/vendor/symfony/console/Formatter/OutputFormatter.php(171): Symfony\Component\Console\Formatter\OutputFormatterStyleStack->pop(Object(Symfony\Component\Console\Formatter\OutputFormatterStyle))
#1 /home/kelunik/GitHub/kelunik/acme-client/vendor/symfony/console/Application.php(669): Symfony\Component\Console\Formatter\OutputFormatter->format('<error>  son</c...')
#2 /home/kelunik/GitHub/kelunik/acme-client/vendor/macfja/phar-builder/app/Application.php(66): Symfony\Component\Console\Application->renderException(Object(Exception), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/kelunik/GitHub/kelunik/acme-client/vendor/macfja/phar-builder/app/Application.php(84): MacFJA\PharBuilder\Application->checkSystem(Object(Symfony\Compon in /home/kelunik/GitHub/kelunik/acme-client/vendor/symfony/console/Formatter/OutputFormatterStyleStack.php on line 87
```

What I did wrong:

```
    "extra": {
        "compression": "GZip",
        "name": "acme.phar",
        "output-dir": "build",
        "include": ["bin", "src", "vendor"],
        "entry-point": "bin/acme"
    }
```

instead of

```
    "extra": {
        "phar-builder": {
            "compression": "GZip",
            "name": "acme.phar",
            "output-dir": "build",
            "include": ["bin", "src", "vendor"],
            "entry-point": "bin/acme"
        }
    }
```

But it doesn't change anything.

**Comment by MacFJA** [comment]
The error is throw when PharBuilder want to display the error message about the fact that you can create Phar archive.
But, still I don't understand why you have an error.

For now you can de-activate the readonly of Phar. It will be go further in the Phar creation.
I keep searching for the origin of the issue

---

The error message that PharBuilder try to display:

> The configuration of your PHP do not authorize PHAR creation. (see phar.readonly in you php.ini)
> Alternatively you can run **php -d phar.readonly=0 vendor/bin/phar-builder package composer.json**.

**Comment by MacFJA** [comment]
Ok, I was able to reproduce your error.
It happen when the error message (in fact any type of message) is cut (due to the console width) before the begin of a closing style tag.

I will remove the style that cause the issue.

EDIT: @kelunik, can you retry with the commit 9efd28e ?

---

If the message is `<style1>Hello World</style1>`, and, due to the console width, the new line is insert before `</style1>`: the error is throw.
But if the new line is inserted after **`<`** of `</style1>` it will not throw an error (but it will have a weird display).

**Comment by kelunik** [comment]
![image](https://cloud.githubusercontent.com/assets/2743004/13900204/bab12606-ee00-11e5-94c0-0a7ccd8c1df1.png)

Looks good. :+1:
