### ISSUE TITLE
Trouble running the app in a headless CI-Server

### ISSUE THREAD

**Issue by heiglandreas** [MacFJA/PharBuilder#30]
Due to https://github.com/MacFJA/PharBuilder/blob/8c348f48e1d501af7f26f8ce794d7815c7f7ab66/app/Commands/Base.php#L380 it is not easily possible to run the app in a headless server-environment like a CI-Server.

I had trouble getting it set up and running on Travis-CI until I dug into the code and added some default values to the config in the ```composer.json```.

The following keys need to be set in the config to run headless, otherwise the check whether the script runs without IO prevents the default settings being used:

* entry-point
* compression
* name
* output-dir
* include
* skip-shebang

It would be great to find that information in the docs somewhere or prevent the check failing a headless build…

**Comment by heiglandreas** [comment]
This would be fixed with #28

**Comment by MacFJA** [comment]
PR #28 have been merge.
But I will also add in the documentation the list of minimum parameters

**Comment by MacFJA** [comment]
@heiglandreas The PR #37 provided changes that completely prevent this issue.

With this PR the `package` command, in headless, can run without any trouble (even if no options are defined in the `composer` extra section) thanks to value guessing and default fallback.

however, the command `build` is design to be use on interactive terminal only, where the `package` command is design to read command option, `composer` extra section and use input (in this order)
