### ISSUE TITLE
"skip-shebang": false doesn't have default

### ISSUE THREAD

**Issue by kelunik** [MacFJA/PharBuilder#38]
`vendor/bin/phar-builder package composer.json` interactively asks for a value even if it should run and use the default value if no `"skip-shebang": false` is present.

**Comment by MacFJA** [comment]
I think I found why this behavoir occurs. I will fix it this week

**Comment by MacFJA** [comment]
With a little delay, the PR #39 will solve your issue.  
I will merge it next week if nobody have issue with it

**Comment by MacFJA** [comment]
@kelunik Did this PR solve your issue?

**Comment by MacFJA** [comment]
I merged the PR #39 

If the issue is still present, please reopen this issue

**Comment by kelunik** [comment]
Will do, haven't had time to test this yet.
