### ISSUE TITLE
Output Directory should be created if non-existent

### ISSUE THREAD

**Issue by kelunik** [MacFJA/PharBuilder#4]
![image](https://cloud.githubusercontent.com/assets/2743004/13900208/fd8698c6-ee00-11e5-8e10-0a709221fc03.png)

Currently, it just fails with an error, that it's not a valid directory. If it doesn't exist (isn't a file), it should be created.

**Comment by MacFJA** [comment]
I added more test on the output directory (see 6e7d0ac):
- Check if the provided path **is a file**
- Check if the provided path **is non-existent**, and **try to create** the directory if needed
- Check if the provided directory **is writable**

**Comment by kelunik** [comment]
[Could you merge it?](https://github.com/MacFJA/PharBuilder/compare/create-ouput-dir+issue-4)

Time for `v0.2.2` then?

**Comment by MacFJA** [comment]
Done and done ! :wink:
