### ISSUE TITLE
Exclude `require-dev` dependencies

### ISSUE THREAD

**Issue by kelunik** [MacFJA/PharBuilder#5]
When building the archive, `require-dev` dependencies should be excluded or at least there should be a flag to do so.

**Comment by MacFJA** [comment]
It will need a full rewrite of my _not really_ composer parser.

Because for now, the whole `vendor` directory is copied (that can also create issue if the composer vendor directory is not `vendor`)

**Comment by kelunik** [comment]
`composer update --no-dev` → create phar → `composer update` would work, if I didn't use `PharBuilder` as `require-dev`, too.

**Comment by MacFJA** [comment]
@kelunik, now your phar will be lot more lighter than before.

The new parser is also more logical and can do lots more :smiley:

**Comment by MacFJA** [comment]
Issue fixed in #10
