### ISSUE TITLE
Not bundling the composer file fails on some dependencies

### ISSUE THREAD

**Issue by PeeHaa** [MacFJA/PharBuilder#50]
I have a dependency in my project which tries to check its own `composer.json` file to get its version.

In [`PharBuilder.php`](https://github.com/MacFJA/PharBuilder/blob/master/app/PharBuilder.php#L446) you specifically exclude composer files from the build.

Is / was there a specific reason for this and if not would you mind if I open a PR to allow for the composer.json file to be included into the build?

I guess it would be neat if it would be part of the configuration at some point, but for now I quick fix by just removing the line would work for me.

**Comment by MacFJA** [comment]
The only reason that I remove `composer.json` (and lock) is to remove _useless_ files.

I assumed that no third-party code will need its composer.json, but you prove me that it's not the case :smile: 

Feel free to open a PR to remove this line.

**Comment by theofidry** [comment]
@MacFJA and on another hand for some tools like PHP-CS-Fixer where compression is disabled they should by all means be excluded along with some unneeded composer related files :/

**Comment by MacFJA** [comment]
@theofidry If dependencies are managed correctly (for example `php-cs-fixer` is set as dev requirement), PharBuilder can exclude all dev dependencies (which is the case by default).

**Comment by theofidry** [comment]
@MacFJA I meant PHP-CS-Fixer as the tool itself for its own PHAR, not as a dep. Their PHAR is not compressed, so excluding files like `composer.json`, `composer.lock`, `installed.json` which are not necessary for the PHAR to run should be excluded otherwise the PHAR size can quickly go up

**Comment by PeeHaa** [comment]
@theofidry Can you confirm my test results in the PR and verify it's *not* a concern please?

**Comment by PeeHaa** [comment]
Also does php-cs-fixer even use this project to build there phar? @theofidry 

As far as I can see they are using box

**Comment by theofidry** [comment]
I'm just sharing this information in case this might be a concern, not to say the `composer.json` should be included or excluded.
