### ISSUE TITLE
No support for Symfony 4

### ISSUE THREAD

**Issue by Westie** [MacFJA/PharBuilder#56]
Hi,

I've been attempting to install this project as a dev dependency but I cannot due to this being locked to Version 2.7+, 3.0+ of Symfony.

I'm inclined to submit a pull request, however in addition your sister project `macfja/symfony-console-filechooser` is also hardcoded to support 2.7+, 3.0+, which makes it just that bit harder to work around.

(Plus, I do not know the source code of this project all that well so I am against bumping up versions of composer without say... running tests or something)

Thank you!

**Comment by theofidry** [comment]
Hi, I would recommend another way than installing it as a dev dependency since there is no advantage in doing so. You can find some alternative install instructions [here](https://github.com/humbug/box/blob/master/doc/installation.md#installation) or more information [here](https://medium.com/@tfidry/managing-your-dependencies-in-php-321d584441ab)

**Comment by MacFJA** [comment]
Hi,

Thank for using the project and reporting this issue!

As @theofidry said, you can install PharBuilder as an external tool (standalone Phar can be found in [release section](https://github.com/MacFJA/PharBuilder/releases))

But I will check if the library use any Symfony 3.4 deprecated code, update if it's the case, and them add Symfony 4 in the constraint (same for `macfja/symfony-console-filechooser`)

When I found time I will continue to work on the rework of the project (which will drop Symfony 2 and 3 compatibility)

**Comment by MacFJA** [comment]
Hi @Westie 

I push a branch with Symfony 4 compatibilty (`sf4-compatibility`).  
Can you check is everything is working correctly with this branch? (I will merge it into master and make a tag if it's all good for you)

**Comment by stmh** [comment]
Hi @MacFJA, 

I tested the branch with a symfony 4.1 application of mine and everything is working fine!

**Comment by Westie** [comment]
Hi @MacFJA, thank you for the quick turn around. I'll give it a try either later on tonight or tomorrow - @stmh's comment looks promising!

**Comment by Westie** [comment]
Hi @MacFJA, I can confirm it works. Thank you!
