### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by kirill-konshin** [MacFJA/PharBuilder#58]
https://github.com/MacFJA/PharBuilder/blob/develop/docs/ComposerJsonOptions.md#full-example

`shebang: false` dose nothing, you have to specify `skip-shebang: true`.

https://github.com/MacFJA/PharBuilder/blob/develop/README.md#command-package

Some CLI options are renamed/missing: `output` has to be `output-dir`, `no-dev` does not exist at all and so on.

**Comment by MacFJA** [comment]
Oh you right!

I will fix it in the next days
