### ISSUE TITLE
White on Green is hard to read

### ISSUE THREAD

**Issue by kelunik** [MacFJA/PharBuilder#6]
![image](https://cloud.githubusercontent.com/assets/2743004/13900276/b5cb2fd6-ee02-11e5-9290-ebb6cc382e41.png)

I suggest using a dark foreground color.

**Comment by MacFJA** [comment]
It really depends of the color scheme of your console but I agree, it's not really readable.

I just open an issue ( #7 ) about that too :smile:

**Comment by MacFJA** [comment]
With the Symfony Style it's lots more readable :wink: 

![output-with-32071ff](https://cloud.githubusercontent.com/assets/1475671/13902151/3c580fbc-ee3d-11e5-964c-3557242a159c.png)
